### ISSUE TITLE
WhenNotification with SymbolCollection will throw exception

### ISSUE THREAD

**Issue by ali50m** [Beckhoff/TF6000_ADS_DOTNET_V4_Samples#1]
I tried the sample code in https://github.com/Beckhoff/TF6000_ADS_DOTNET_V4_Samples/blob/main/Sources/BaseSamples/Reactive/Program.cs,
find it doesn`t work with my TC2 project. (I don`t have a TC3 envirement, only a VM with TC2 installed).

For simplicity, I wrote a similar sample with TC2 project in this [repo](https://github.com/ali50m/Tc2ArrayNotification/). It`s easy to see the the WhenNotification will cause exception when there are more than one element in the SymbolCollection.

**Comment by ali50m** [comment]
![Snipaste_2021-12-29_10-12-51](https://user-images.githubusercontent.com/9393831/147621773-88cea192-141d-4d89-91e5-11ad2a7d84f4.png)

**Comment by RalfHeitmann** [comment]
Thanks for reporting this. Please have a look at nuget.org. The version 4.4.19 of the **Beckhoff.TwinCAT.Ads.Reactive package** should not show this behaviour anymore.
