### ISSUE TITLE
WPFConnectionObserver not work

### ISSUE THREAD

**Issue by ali50m** [Beckhoff/TF6000_ADS_DOTNET_V4_Samples#2]
The Config and Run button doesn`t work, will cause failure and pop up "DeviceInvalidState". 
The Reset button works as expected.

Tested on CX2020 with Twincat2.

![failure](https://user-images.githubusercontent.com/9393831/148021970-0d7d8968-8b7d-40a5-8ca4-8e63472724ba.png)

**Comment by RalfHeitmann** [comment]
Seems that the Sample was tested originally against a Plc AdsServer not against Port 10000 (SystemService). I corrected the sample for Port 10000. Please be aware that other AdsServer (like the Plc) behave differently with "WriteControl".
