### ISSUE TITLE
exception when running AdsServerSample

### ISSUE THREAD

**Issue by ali50m** [Beckhoff/TF6000_ADS_DOTNET_V4_Samples#3]
Clone this repro, open Test.AdsServerClr4.sln with vs2022 community (17.2.6). Without any modification to this project, just hit F5. It will throw exception like below. Could you please let me know how to start this sample? 

![image](https://user-images.githubusercontent.com/9393831/181749695-af612413-85fb-4666-aa45-780b438ab46c.png)

what has been installed:
TwinCAT 2.11 x64 Engineering v2.11.2307.0

**Comment by RalfHeitmann** [comment]
Actually there are two problems here:

1. With the 'Any CPU' platform settings, you start a 64-bit process as environment for the AdsServer. The Installation of TwinCAT 2.11 x64 Engineering installation has only the base components for 32-Bit installed. You can see this in the C:\TwinCAT\Common32 and C:\TwinCAT\Common64 folders. The AdsServer base component uses the native TcAmsServer.dll from these folders and only the Common32 version is present in the installation. Loading this into a 64-Bit process throws a BadImageException
2. You should set the Debug platform settings from 'Any CPU' to 'x86' to force a 32-bit process. Unfortunately there is an error in the solution configuration of the sample that loads a 64-bit process even if you change the platform. I will correct this. In the meanwhile you could recreate the 'X86' configuration via the VS Solution Configuration manager and force the x86 code creation. With that setting properly in place, the sample starts ...

**Comment by RalfHeitmann** [comment]
For information, a TwinCAT 3 installation supports both 32-bit and 64-Bit AdsServers (64-bit preferred)
